// ── VENUE COORDINATES, NEIGHBORHOODS & IMAGES ────────────────────────────────
const HOOD_COLORS = {
  'South Beach':'#FF6B9D','Downtown':'#64c8ff','Wynwood':'#1DB954',
  'Hialeah':'#F5A623','Mid-Beach':'#b464ff','Islands':'#00CED1','Little River':'#ff6464',
};

const TYPE_IMAGES = {
  pool:'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=400&h=160&fit=crop&q=80',
  club:'https://images.unsplash.com/photo-1571266028243-3116f2d05999?w=400&h=160&fit=crop&q=80',
  warehouse:'https://images.unsplash.com/photo-1504509546545-e000b4a62425?w=400&h=160&fit=crop&q=80',
  cruise:'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&h=160&fit=crop&q=80',
  openair:'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=400&h=160&fit=crop&q=80',
  festival:'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=160&fit=crop&q=80',
};

const VENUE_CROWD = {
  "Club Space": "Tech bros who 'just moved to Brickell', European house heads who haven't slept since Tuesday, and that one legend who's been dancing since the last closing party.",
  "Space Miami": "Tech bros who 'just moved to Brickell', European house heads who haven't slept since Tuesday, and that one legend who's been dancing since the last closing party.",
  "E11EVEN Miami": "Bachelor parties who peaked at pregame, bottle-service warriors who can't name the DJ, and one actual music fan in the corner questioning every life decision.",
  "LIV Nightclub": "Instagram models, crypto bros celebrating a 'dip buy', and people who spent more on the table than their round-trip flight.",
  "Sagamore Hotel": "Influencers photographing their rosé, A&R scouts pretending not to network, and the one guy in a full suit because he 'came straight from WMC.'",
  "Surfcomber Hotel": "Music bloggers, sunburnt Brits on day two of no sleep, and the DJ's manager doing a headcount from behind oversized sunglasses.",
  "National Hotel": "People who think 'HIIDE' is a clothing brand, TikTok DJs filming content between sets, and the poolside veteran who's done this since Ultra was on the beach.",
  "Factory Town": "Berghain cosplayers, people who claim they 'only listen to vinyl', and warehouse warriors who brought their own earplugs and water bottles.",
  "Factory Town (Infinity Room)": "Berghain cosplayers, people who claim they 'only listen to vinyl', and warehouse warriors who brought their own earplugs and water bottles.",
  "Hialeah Park Casino": "People who looked at Google Maps twice, Uber drivers who've never been out this far, and the deep house heads who'd follow Black Coffee to a parking garage.",
  "M2": "All-black outfit purists, techno elitists who think everything else is 'commercial', and the one person at 5am making uncomfortably intense eye contact.",
  "M2 Miami": "All-black outfit purists, techno elitists who think everything else is 'commercial', and the one person at 5am making uncomfortably intense eye contact.",
  "Jungle Island": "Wellness influencers who came for the 'nature vibes', Burning Man regulars in full festival gear, and confused families who didn't know the island was a rave today.",
  "Kimpton EPIC Hotel": "WMC badge holders, Beatport employees on their lunch break, and DJs casually dropping that they 'have a set later.'",
  "Kimpton EPIC Hotel Pool": "WMC badge holders, Beatport employees on their lunch break, and DJs casually dropping that they 'have a set later.'",
  "MANA Wynwood": "Art school graduates, people who 'discovered' bass music last year, and the local Wynwood cat who has somehow outlived three venue rebrands.",
  "Toe Jam XL": "People who actually know the B2B partners' solo work, OG ravers reliving their golden era, and the friend who 'just wants one drink' at midnight.",
  "Toe Jam Backlot": "People who actually know the B2B partners' solo work, OG ravers reliving their golden era, and the friend who 'just wants one drink' at midnight.",
  "James L. Knight Center": "Seated house music boomers, people who cried during 'Gypsy Woman' in 1991 and will cry again tonight, and their reluctant adult children.",
  "Fooqs Miami (Lion's Den)": "Minimal techno elitists who flew in from Berlin, restaurant regulars who had no idea about the takeover, and people who just wanted the tuna tartare.",
  "RC Cola Plant": "Warehouse purists, the 'I liked Gordo before he was Gordo' crowd, and people who are somehow always cold in Miami.",
  "Wynwood Marketplace": "Open-air optimists with SPF 50 and bucket hats, Anjunadeep devotees who brought a blanket to lie on, and couples who think this counts as a date.",
  "UVA Wynwood": "Desert Hearts cult members in tie-dye, people who say 'namaste' unironically, and the guy doing contact juggling near the speaker stack.",
  "Nikki Beach": "Euro tourists in white linen, people who've been 'meaning to come here for years', and EDX fans who followed the brand from Ibiza.",
  "ZeyZey": "Vinyl diggers, people with obscure label tattoos, and bartenders from other Wynwood venues on their night off.",
  "1-800-LUCKY": "Wynwood food hall regulars who stayed for the music, progressive house heads, and people eating ramen between sets.",
  "Mazuma": "Trance purists, psytrance warriors, and the 'this isn't real trance' guy who showed up to every event this week.",
  "CLUTCH": "People who memorized the Anjunabeats catalog, trance fans with glowsticks in 2026, and the couple who met at ASOT 900.",
  "MIDLINE Miami": "Progressive house evangelists, people who think Audien doesn't get enough credit, and Seven Lions fans with emotional support playlists.",
  "The Ground": "Neoperreo heads, people in platform boots, and confused EDM tourists who walked into the wrong room at Space.",
  "The Triangle at Little River": "Disco elders, Soul Clap vinyl collectors, and people who think Little River is 'the new Wynwood' every single year.",
  "Jolene Sound Room": "Actual DJs checking out the competition, tech house connoisseurs, and the bartender who's heard more b2b sets than anyone alive.",
  "MAD Club Wynwood": "People who 'prefer the smaller rooms', bass heads who lost their friends at MANA, and promoters handing out flyers for tomorrow's party.",
  "MAD LIVE": "Anjunabeats devotees, Mat Zo apologists, and people who will absolutely cry during the breakdown.",
  "Mode": "Underground purists, people who rate events on RA, and the doorman who's seen everything.",
  "DUA Miami": "People who found out about this from TikTok, the 'we're just checking it out' crew, and pool party hoppers on their third venue of the day.",
  "Sable Miami": "Ministry of Sound pilgrims, Dennis Ferrer disciples, and UK expats who keep saying 'this reminds me of Fabric.'",
};

const TYPE_CROWD = {
  pool: "Sunburnt ravers in designer swimwear, people who can't decide between the pool and the DJ, and that one person who brought a waterproof phone case for stories.",
  club: "All-black fits, people checking RA on their phones between sets, and bartenders who know more about the lineup than half the crowd.",
  warehouse: "People who brought earplugs and a water bottle, warehouse veterans who've 'seen better sound systems', and someone definitely wearing a hi-vis vest as fashion.",
  cruise: "People who love techno but hate the ocean, couples who thought this was a 'romantic sunset cruise', and DJs who won't stop mentioning they're 'playing on a boat.'",
  openair: "Golden hour photographers, people in bucket hats who think they're at Coachella, and the one person who brought a camping chair.",
  festival: "Confetti-covered lunatics, people in costumes that seemed like a good idea 6 hours ago, and someone who lost a shoe but gained a new best friend.",
};

const VENUE_DATA = {
  "Club Space":{lat:25.7858,lng:-80.1912,hood:'Downtown',img:'https://images.unsplash.com/photo-1598387993441-a364f854c3e1?w=400&h=160&fit=crop&q=80'},
  "E11EVEN Miami":{lat:25.7852,lng:-80.1918,hood:'Downtown',img:'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=400&h=160&fit=crop&q=80'},
  "Kimpton EPIC Hotel":{lat:25.7685,lng:-80.1875,hood:'Downtown'},
  "Kimpton EPIC Hotel Pool":{lat:25.7686,lng:-80.1876,hood:'Downtown'},
  "James L. Knight Center":{lat:25.7648,lng:-80.1922,hood:'Downtown'},
  "M2":{lat:25.7862,lng:-80.1905,hood:'Downtown'},
  "M2 Miami":{lat:25.7862,lng:-80.1905,hood:'Downtown'},
  "Space Miami":{lat:25.7858,lng:-80.1912,hood:'Downtown',img:'https://images.unsplash.com/photo-1598387993441-a364f854c3e1?w=400&h=160&fit=crop&q=80'},
  "Sagamore Hotel":{lat:25.7938,lng:-80.1301,hood:'South Beach',img:'https://images.unsplash.com/photo-1572331165267-854da2b021b1?w=400&h=160&fit=crop&q=80'},
  "Surfcomber Hotel":{lat:25.7908,lng:-80.1296,hood:'South Beach'},
  "Surfcomber":{lat:25.7908,lng:-80.1296,hood:'South Beach'},
  "National Hotel":{lat:25.7868,lng:-80.1308,hood:'South Beach'},
  "Nikki Beach":{lat:25.7688,lng:-80.1318,hood:'South Beach',img:'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&h=160&fit=crop&q=80'},
  "Moxy South Beach":{lat:25.7835,lng:-80.1312,hood:'South Beach'},
  "Sable Miami":{lat:25.7965,lng:-80.1965,hood:'Wynwood'},
  "LIV Nightclub":{lat:25.8128,lng:-80.1228,hood:'Mid-Beach',img:'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=400&h=160&fit=crop&q=80'},
  "UVA Wynwood":{lat:25.8008,lng:-80.1988,hood:'Wynwood'},
  "MANA Wynwood":{lat:25.7988,lng:-80.1998,hood:'Wynwood',img:'https://images.unsplash.com/photo-1504509546545-e000b4a62425?w=400&h=160&fit=crop&q=80'},
  "MAD Club Wynwood":{lat:25.8012,lng:-80.1992,hood:'Wynwood'},
  "Wynwood Marketplace":{lat:25.8022,lng:-80.1982,hood:'Wynwood'},
  "ZeyZey":{lat:25.7992,lng:-80.1978,hood:'Wynwood'},
  "1-800-LUCKY":{lat:25.8018,lng:-80.1990,hood:'Wynwood'},
  "Toe Jam XL":{lat:25.7982,lng:-80.1972,hood:'Wynwood'},
  "Toe Jam Backlot":{lat:25.7984,lng:-80.1974,hood:'Wynwood'},
  "Jolene Sound Room":{lat:25.7978,lng:-80.1988,hood:'Wynwood'},
  "MAD LIVE":{lat:25.8018,lng:-80.1998,hood:'Wynwood'},
  "MIDLINE Miami":{lat:25.7955,lng:-80.1965,hood:'Wynwood'},
  "Mazuma":{lat:25.7948,lng:-80.1955,hood:'Wynwood'},
  "CLUTCH":{lat:25.7942,lng:-80.1948,hood:'Wynwood'},
  "Mode":{lat:25.7962,lng:-80.1958,hood:'Wynwood'},
  "RC Cola Plant":{lat:25.8105,lng:-80.2008,hood:'Wynwood'},
  "Factory Town":{lat:25.8632,lng:-80.2822,hood:'Hialeah',img:'https://images.unsplash.com/photo-1504509546545-e000b4a62425?w=400&h=160&fit=crop&q=80'},
  "Factory Town (Infinity Room)":{lat:25.8634,lng:-80.2824,hood:'Hialeah',img:'https://images.unsplash.com/photo-1504509546545-e000b4a62425?w=400&h=160&fit=crop&q=80'},
  "Hialeah Park Casino":{lat:25.8552,lng:-80.2782,hood:'Hialeah'},
  "Jungle Island":{lat:25.7872,lng:-80.1738,hood:'Islands',img:'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=400&h=160&fit=crop&q=80'},
  "Watson Island Park":{lat:25.7868,lng:-80.1732,hood:'Islands'},
  "Yacht / Miami":{lat:25.7748,lng:-80.1808,hood:'Islands'},
  "Luxury Yacht":{lat:25.7752,lng:-80.1812,hood:'Islands'},
  "Hyatt Regency Dock":{lat:25.7668,lng:-80.1858,hood:'Downtown'},
  "Fooqs Miami (Lion's Den)":{lat:25.8202,lng:-80.1952,hood:'Little River'},
  "The Triangle at Little River":{lat:25.8322,lng:-80.1892,hood:'Little River'},
  "The Ground":{lat:25.7856,lng:-80.1914,hood:'Downtown'},
  "Joia Beach":{lat:25.7878,lng:-80.1728,hood:'Islands'},
  "Astra Rooftop Garden":{lat:25.7948,lng:-80.1968,hood:'Wynwood'},
  "Mad Radio":{lat:25.8015,lng:-80.1990,hood:'Wynwood'},
  "DUA Miami":{lat:25.7958,lng:-80.1972,hood:'Wynwood'},
  "Clevelander":{lat:25.7808,lng:-80.1305,hood:'South Beach'},
};

// ── HARRY POTTER CHARACTER DATA ──────────────────────────────────────────────
const HP_CHARACTERS = [
  {name:'Luna Lovegood',house:'Ravenclaw',emoji:'🌙',quote:"You're just as sane as I am.",
    genres:['trance','progressive','melodic','ambient','experimental'],
    reason:"Your eclectic, otherworldly taste shows you march to the beat of your own drum. Like Luna, you find beauty in sounds others overlook and aren't afraid to explore the weird and wonderful."},
  {name:'Severus Snape',house:'Slytherin',emoji:'🖤',quote:"Always.",
    genres:['techno','minimal','industrial','dark techno'],
    reason:"Behind your dark, intense exterior lies deep emotional complexity. Like Snape, you're drawn to the underground — disciplined, precise, and deeply passionate beneath the surface."},
  {name:'Fred & George Weasley',house:'Gryffindor',emoji:'🎪',quote:"I solemnly swear that I am up to no good.",
    genres:['bass','hiphop','trap','dubstep','jersey club'],
    reason:"Pure chaotic energy! Like the Weasley twins, your taste is all about maximum fun, surprise drops, and keeping everyone on their toes. You're the life of every party."},
  {name:'Hermione Granger',house:'Gryffindor',emoji:'📚',quote:"It's leviOsa, not levioSA.",
    genres:['progressive','deephouse','melodic techno','electronica'],
    reason:"Analytical and refined, your taste reveals someone who appreciates depth and complexity. Like Hermione, you've done your homework — you know every B-side and every label."},
  {name:'Sirius Black',house:'Gryffindor',emoji:'🐕',quote:"The ones that love us never really leave us.",
    genres:['techhouse','minimal','underground','acid'],
    reason:"A rebel with impeccable taste. Like Sirius, you live for the underground — warehouse raves, secret sets, and the thrill of discovery. Convention bores you."},
  {name:'Dumbledore',house:'Gryffindor',emoji:'🧙',quote:"Happiness can be found even in the darkest of times, if one only remembers to turn on the light.",
    genres:['disco','deephouse','soulful house','jazz','classic house'],
    reason:"Your taste spans decades and genres with effortless wisdom. Like Dumbledore, you see the bigger picture — appreciating how all music connects, from disco's origins to modern house."},
  {name:'Draco Malfoy',house:'Slytherin',emoji:'🐍',quote:"My father will hear about this!",
    genres:['techno','tech house','high-tech minimal','dark progressive'],
    reason:"Sleek, polished, and a little dangerous. Like Draco, your taste is refined but with an edge — you gravitate toward the dark and exclusive. VIP energy only."},
  {name:'Hagrid',house:'Gryffindor',emoji:'🏔️',quote:"I should not have said that.",
    genres:['afrohouse','world','organic house','tribal'],
    reason:"Big-hearted and earthy, your taste reflects a deep connection to rhythm and roots. Like Hagrid, you bring warmth to every room and find magic in nature's pulse."},
  {name:'Neville Longbottom',house:'Gryffindor',emoji:'🌱',quote:"Why is it always me?",
    genres:['deephouse','lo-fi house','downtempo','chill'],
    reason:"Underrated and quietly brilliant. Like Neville, your understated taste hides a deep well of quality. You don't need the spotlight — the music speaks for itself."},
  {name:'Ginny Weasley',house:'Gryffindor',emoji:'🔥',quote:"The thing about growing up with Fred and George is that you sort of start thinking anything's possible.",
    genres:['hard techno','rave','hardstyle','peak time'],
    reason:"Fierce, relentless, and full of fire. Like Ginny, you've got more energy than anyone expects. The harder the beat, the harder you go."},
  {name:'Tonks',house:'Hufflepuff',emoji:'💜',quote:"Don't call me Nymphadora!",
    genres:['electro','breakbeat','uk garage','eclectic'],
    reason:"Genre-fluid and impossible to pin down. Like Tonks, you shapeshift between styles — one minute it's garage, the next it's electro. Your taste defies categorization."},
  {name:'Dobby',house:'Hufflepuff',emoji:'🧦',quote:"Dobby is a free elf!",
    genres:['trance','uplifting','vocal trance','euphoric'],
    reason:"Pure-hearted and deeply emotional. Like Dobby, your taste is driven by feeling — you chase euphoria, uplift, and those moments where the music sets you free."},
  {name:'McGonagall',house:'Gryffindor',emoji:'🐱',quote:"Have a biscuit, Potter.",
    genres:['classic house','garage','soulful','chicago house'],
    reason:"No-nonsense quality with impeccable standards. Like McGonagall, you respect the foundations — classic house, proper DJing, and the kind of music that stands the test of time."},
  {name:'Bellatrix Lestrange',house:'Slytherin',emoji:'⚡',quote:"I killed Sirius Black!",
    genres:['industrial','hardstyle','gabber','hard techno','noise'],
    reason:"Unhinged, intense, and absolutely magnetic. Like Bellatrix, your taste is extreme and unapologetic. The louder, harder, and more chaotic, the better."},
  {name:'Harry Potter',house:'Gryffindor',emoji:'⚡',quote:"I must not tell lies.",
    genres:['house','tech house','melodic house','mainstream'],
    reason:"Versatile and universally loved, but with genuine depth. Like Harry, you're drawn to the heart of the action — popular picks with real substance behind them."},
  {name:'Ron Weasley',house:'Gryffindor',emoji:'♟️',quote:"Bloody hell!",
    genres:['tech house','party','festival','edm','big room'],
    reason:"Loyal, fun-loving, and always down for a good time. Like Ron, you don't overthink it — if the tune slaps and the crowd's moving, you're in. Pure vibes."},
  {name:'Lupin',house:'Gryffindor',emoji:'🐺',quote:"The very best of us sometimes eat chocolate.",
    genres:['deep house','organic','downtempo','ambient house'],
    reason:"Thoughtful and a bit melancholic, but with a wild side. Like Lupin, your taste shifts between gentle introspection and unleashed energy when the moon is right."},
  {name:'Cedric Diggory',house:'Hufflepuff',emoji:'🏆',quote:"Take my body back to my father.",
    genres:['melodic house','progressive house','anthemic','vocal house'],
    reason:"Golden and polished, your taste is all about those soaring, anthemic moments. Like Cedric, you represent the best of the best — quality that everyone can appreciate."},
  {name:'Newt Scamander',house:'Hufflepuff',emoji:'🦎',quote:"My philosophy is that worrying means you suffer twice.",
    genres:['ambient','experimental','leftfield','idm','glitch'],
    reason:"Curious and gentle, you seek out the strange and beautiful. Like Newt, your taste leads you to musical creatures most people don't even know exist."},
  {name:'Molly Weasley',house:'Gryffindor',emoji:'🏠',quote:"NOT MY DAUGHTER, YOU—",
    genres:['disco','funk','soul','gospel house','classic'],
    reason:"Warm, nurturing, but fierce when it counts. Like Molly, your taste is rooted in timeless classics — the kind of music that brings everyone together and feels like home."},
];

// ── EVENTS ───────────────────────────────────────────────────────────────────
const EVENTS = [
  // ── TUESDAY MARCH 24 ──────────────────────────────────────────────────────
  {id:1,day:'tue',dayLabel:'Tue Mar 24',name:"Experts Only: Club Space Takeover",venue:"Club Space",type:'club',time:"11pm–8pm (21hrs)",artists:"John Summit, ANNA, DJ Tennis, Hot Since 82, Layton Giordani, SG Lewis, AYYBO, Max Styler, Marte, OMRI",genre:['techhouse','deephouse'],matchKeywords:['john summit','tech house','anna','dj tennis','hot since 82','layton giordani','sg lewis','omri'],summary:"Marathon 21-hour full venue takeover. All 3 rooms under John Summit's Experts Only banner.",hype:5,mentions:7,bandwagon:5},
  {id:2,day:'tue',dayLabel:'Tue Mar 24',name:"Beatport × Mood Child Pool Party",venue:"Kimpton EPIC Hotel",type:'pool',time:"5–10pm",artists:"DJ Sneak, Jean Pierre, Manda Moor, Ms. Mada, Sirus Hood",genre:['deephouse','techhouse'],matchKeywords:['dj sneak','chicago house','house music','sirus hood'],summary:"Classic house vibes from DJ Sneak poolside at the EPIC.",hype:3,mentions:3,bandwagon:3},
  {id:3,day:'tue',dayLabel:'Tue Mar 24',name:"Luuk van Dijk: Get Closer",venue:"Jolene Sound Room",type:'club',time:"10pm–4am",artists:"Luuk van Dijk, Elliot Schooling, Julian Anthony, Laidlaw, Liam Palmer",genre:['techhouse','deephouse'],matchKeywords:['luuk van dijk','tech house'],summary:"Intimate club — one of the week's most refined tech house bookings.",hype:4,mentions:2,bandwagon:2},
  {id:4,day:'tue',dayLabel:'Tue Mar 24',name:"STMPD RCRDS Showcase",venue:"Surfcomber Hotel",type:'pool',time:"12pm–11pm",artists:"DubVision, Third Party, Matisse & Sadko, Julian Jordan, VisionV, Telykast, Justin Mylo",genre:['progressive','melodic'],matchKeywords:['dubvision','third party','matisse sadko','julian jordan','stmpd'],summary:"Martin Garrix's STMPD RCRDS label showcase poolside.",hype:3,mentions:3,bandwagon:3},
  {id:5,day:'tue',dayLabel:'Tue Mar 24',name:"Satoshi Tomiie: NOMAD Talent",venue:"Mode",type:'club',time:"10pm–5am",artists:"Satoshi Tomiie, Melody, Ohm Hourani, Kurilo",genre:['deephouse','minimal'],matchKeywords:['satoshi tomiie','deep house'],summary:"Japanese house legend Satoshi Tomiie headlines an intimate underground showcase.",hype:3,mentions:1,bandwagon:2},

  // ── WEDNESDAY MARCH 25 ─────────────────────────────────────────────────────
  {id:6,day:'wed',dayLabel:'Wed Mar 25',name:"20 Years of Rekids (Beatport)",venue:"Kimpton EPIC Hotel Pool",type:'pool',time:"3–10pm",artists:"Danny Tenaglia, Radio Slave b2b DJ Minx, Doc Martin b2b Tal Fussman, Anja Schneider b2b William Kiss",genre:['techhouse','deephouse','minimal'],matchKeywords:['danny tenaglia','radio slave','rekids','anja schneider','doc martin'],summary:"Legendary label Rekids turns 20. Stacked b2b lineup poolside.",hype:5,mentions:4,bandwagon:3},
  {id:7,day:'wed',dayLabel:'Wed Mar 25',name:"Oliver Heldens at E11EVEN",venue:"E11EVEN Miami",type:'club',time:"8pm–10am",artists:"Oliver Heldens, Mister Gray",genre:['techhouse','deephouse'],matchKeywords:['oliver heldens','house','future house'],summary:"E11EVEN's 24hr format with Oliver Heldens headlining.",hype:4,mentions:3,bandwagon:4},
  {id:8,day:'wed',dayLabel:'Wed Mar 25',name:"DJ Mag Pool Party: Cloonee",venue:"Sagamore Hotel",type:'pool',time:"1pm–11pm",artists:"Cloonee, Ben Sterling, Omar+, Salomé Le Chat, Gio Elia, Obskür",genre:['techhouse'],matchKeywords:['cloonee','ben sterling','tech house','hellbent'],summary:"DJ Mag's flagship pool party. Cloonee is the 2026 cover star.",hype:5,mentions:5,bandwagon:4},
  {id:9,day:'wed',dayLabel:'Wed Mar 25',name:"Crystal Waters: I Am House Orchestrated",venue:"James L. Knight Center",type:'club',time:"7–11pm",artists:"Crystal Waters, Barbara Tucker, Byron Stingily, CeCe Peniston, Duane Harden",genre:['disco','deephouse'],matchKeywords:['crystal waters','gospel house','barbara tucker','classic house','cece peniston'],summary:"Rare live orchestrated house with legends.",hype:4,mentions:3,bandwagon:3},
  {id:10,day:'wed',dayLabel:'Wed Mar 25',name:"Justice (DJ Set) at Factory Town",venue:"Factory Town (Infinity Room)",type:'warehouse',time:"10pm–7am",artists:"Justice, Chris Avantgarde, Camoufly, Alignment, Cloudy, ATRIP",genre:['techno','progressive'],matchKeywords:['justice','french house','electro','chris avantgarde'],summary:"French icons Justice in Factory Town's Infinity Room. One of the week's rarest bookings.",hype:5,mentions:5,bandwagon:3},
  {id:11,day:'wed',dayLabel:'Wed Mar 25',name:"Converge: Richie Hawtin b2b Dubfire",venue:"Fooqs Miami (Lion's Den)",type:'club',time:"9pm–3am",artists:"Richie Hawtin b2b Dubfire, Magda, Satoshi Tomiie, DJ Nigiri",genre:['techno','minimal'],matchKeywords:['richie hawtin','dubfire','magda','minimal techno','plastikman'],summary:"Richie Hawtin and Dubfire b2b in a restaurant-turned-club.",hype:5,mentions:5,bandwagon:2},
  {id:12,day:'wed',dayLabel:'Wed Mar 25',name:"Carlita + LP Giobbi",venue:"LIV Nightclub",type:'club',time:"11:30pm–5am",artists:"Carlita, LP Giobbi",genre:['deephouse','melodic'],matchKeywords:['carlita','lp giobbi','melodic house'],summary:"Two rising stars share a bill at LIV.",hype:4,mentions:3,bandwagon:3},
  {id:13,day:'wed',dayLabel:'Wed Mar 25',name:"HUGEL's Make The Girls Dance",venue:"Space Miami",type:'club',time:"11pm–8pm",artists:"HUGEL",genre:['techhouse'],matchKeywords:['hugel','tech house','french house'],summary:"HUGEL takes over Space for a marathon session.",hype:3,mentions:2,bandwagon:3},
  {id:14,day:'wed',dayLabel:'Wed Mar 25',name:"Two And A Half Cats: Luciano",venue:"Surfcomber Hotel",type:'pool',time:"12pm–11pm",artists:"Luciano, Mendoza, MIGUELLE & TONS, Miluhska, Noel",genre:['deephouse','minimal'],matchKeywords:['luciano','cadenza','minimal house'],summary:"Luciano headlines a poolside session at the Surfcomber.",hype:4,mentions:2,bandwagon:3},
  {id:15,day:'wed',dayLabel:'Wed Mar 25',name:"RESISTANCE Miami Music Week",venue:"M2",type:'club',time:"10pm–5am",artists:"999999999, Juliet Fox, Yousuke Yukimatsu",genre:['techno'],matchKeywords:['999999999','juliet fox','hard techno','resistance'],summary:"Opening night of Ultra's RESISTANCE. Hard techno at M2.",hype:4,mentions:4,bandwagon:3},
  {id:16,day:'wed',dayLabel:'Wed Mar 25',name:"Balance Miami: Guy J & Guy Mantzur",venue:"1-800-LUCKY",type:'club',time:"4pm–3am",artists:"Guy J, Guy Mantzur, Ezequiel Arias, Lucas Zárate, Niki Sadeki",genre:['progressive','melodic'],matchKeywords:['guy j','guy mantzur','progressive house','balance'],summary:"Progressive house legends in an intimate Wynwood setting.",hype:3,mentions:2,bandwagon:2},
  {id:17,day:'wed',dayLabel:'Wed Mar 25',name:"Incorrect Music: Cristoph & Friends",venue:"Mode",type:'club',time:"10pm–5am",artists:"Cristoph, Anthony Attalla, Carlo Lio, Dabura, Dillon Nathaniel",genre:['techhouse','progressive'],matchKeywords:['cristoph','carlo lio','anthony attalla','dillon nathaniel'],summary:"Cristoph headlines the Incorrect Music showcase.",hype:3,mentions:2,bandwagon:2},
  {id:18,day:'wed',dayLabel:'Wed Mar 25',name:"Coldharbour Night: BT",venue:"Mazuma",type:'club',time:"9pm–5am",artists:"BT, Dave Neven, Mike Efex, Tim Clark, Claudia Pavel, Pavlo Vicci",genre:['trance','progressive'],matchKeywords:['bt','markus schulz','coldharbour','trance'],summary:"Coldharbour label showcase with trance legend BT headlining.",hype:3,mentions:2,bandwagon:3},
  {id:19,day:'wed',dayLabel:'Wed Mar 25',name:"Tokimonsta: Young Art Records",venue:"ZeyZey",type:'club',time:"8pm–2am",artists:"Tokimonsta",genre:['bass','deephouse'],matchKeywords:['tokimonsta','brainfeeder','experimental'],summary:"Tokimonsta brings Young Art Records to ZeyZey.",hype:3,mentions:2,bandwagon:1},
  {id:20,day:'wed',dayLabel:'Wed Mar 25',name:"Perreo Del Futuro: Six Sex",venue:"The Ground",type:'club',time:"11pm–5am",artists:"Six Sex",genre:['bass','hiphop'],matchKeywords:['neoperreo','reggaeton','six sex'],summary:"Neoperreo: perreo meets bass-heavy club sounds and hyperpop.",hype:3,mentions:3,bandwagon:1},

  // ── THURSDAY MARCH 26 ──────────────────────────────────────────────────────
  {id:21,day:'thu',dayLabel:'Thu Mar 26',name:"Beatport: Hot Creations × TSZR",venue:"Kimpton EPIC Hotel Pool",type:'pool',time:"3–10pm",artists:"Skream b2b L.P. Rhythm, Sidney Charles b2b Fleur Shore, Elliot Schooling b2b Liam Palmer, Airrica",genre:['techhouse','deephouse'],matchKeywords:['hot creations','jamie jones','skream','sidney charles'],summary:"Jamie Jones' Hot Creations meets TSZR poolside.",hype:5,mentions:4,bandwagon:3},
  {id:22,day:'thu',dayLabel:'Thu Mar 26',name:"Defected Miami: Loco Dice",venue:"Sagamore Hotel",type:'pool',time:"1–11pm",artists:"Loco Dice, Andrea Oliva, Harry Romero, HoneyLuv, Kellie Allen",genre:['deephouse','disco','techhouse'],matchKeywords:['defected','house music','soulful house','loco dice','harry romero','honeyluv'],summary:"Defected Records Sagamore takeover. Loco Dice headlines.",hype:5,mentions:5,bandwagon:3},
  {id:23,day:'thu',dayLabel:'Thu Mar 26',name:"Nora En Pure Presents Purified Miami",venue:"Jungle Island",type:'openair',time:"7pm–12am",artists:"Nora En Pure, Eli & Fur, Fideles, Dosem, Corren Cavini, Jack Emery",genre:['melodic','deephouse'],matchKeywords:['nora en pure','eli & fur','fideles','dosem','melodic house','purified'],summary:"Nora En Pure's Purified at Jungle Island.",hype:5,mentions:4,bandwagon:3},
  {id:24,day:'thu',dayLabel:'Thu Mar 26',name:"Pardon My French",venue:"Toe Jam XL",type:'club',time:"8pm–3am",artists:"DJ Snake b2b A-Trak, Dillon Francis b2b Flosstradamus, TroyBoi, Flowdan, Chuwe",genre:['hiphop','bass'],matchKeywords:['dj snake','a-trak','dillon francis','flosstradamus','troyboi','pardon my french'],summary:"DJ Snake b2b A-Trak + Dillon Francis b2b Flosstradamus. Legendary.",hype:5,mentions:5,bandwagon:5},
  {id:25,day:'thu',dayLabel:'Thu Mar 26',name:"MoBlack Records",venue:"Toe Jam Backlot",type:'club',time:"8pm–3am",artists:"MoBlack, Francis Mercier, Ape Drums b2b Caiiro",genre:['afrohouse','deephouse'],matchKeywords:['moblack','francis mercier','caiiro','afro house','ape drums'],summary:"Afro-house's most beloved label. Deep, rhythm-driven.",hype:4,mentions:3,bandwagon:2},
  {id:26,day:'thu',dayLabel:'Thu Mar 26',name:"Gorgon City: Enter the Realm",venue:"Toe Jam Backlot",type:'club',time:"8pm–4am",artists:"Gorgon City, SG Lewis, Azzecca, Jackie Hollander, Silva Bumpa",genre:['deephouse','techhouse'],matchKeywords:['gorgon city','sg lewis','uk house'],summary:"Gorgon City with SG Lewis support.",hype:4,mentions:3,bandwagon:4},
  {id:27,day:'thu',dayLabel:'Thu Mar 26',name:"deadmau5 at E11EVEN",venue:"E11EVEN Miami",type:'club',time:"8pm–10am",artists:"deadmau5",genre:['progressive','techno'],matchKeywords:['deadmau5','mau5trap','progressive house'],summary:"deadmau5 marathon overnight at E11EVEN.",hype:5,mentions:4,bandwagon:5},
  {id:28,day:'thu',dayLabel:'Thu Mar 26',name:"Cloonee Presents Hellbent",venue:"Space Miami",type:'club',time:"11pm–8pm",artists:"Cloonee, CamelPhat, L.P. Rhythm, Adam Ten, Cole Terrazas",genre:['techhouse','minimal'],matchKeywords:['cloonee','camelphat','hellbent','tech house'],summary:"Cloonee's Hellbent at Space with CamelPhat. Marathon format.",hype:5,mentions:4,bandwagon:4},
  {id:29,day:'thu',dayLabel:'Thu Mar 26',name:"RESISTANCE: Eric Prydz & Argy",venue:"M2",type:'club',time:"10pm–5am",artists:"Eric Prydz, Argy, Jeremy Olander",genre:['progressive','techno'],matchKeywords:['eric prydz','argy','jeremy olander','resistance','cirez d'],summary:"Eric Prydz and Argy headline RESISTANCE.",hype:5,mentions:5,bandwagon:4},
  {id:30,day:'thu',dayLabel:'Thu Mar 26',name:"Toolroom Miami Open Air",venue:"Wynwood Marketplace",type:'openair',time:"3pm–12am",artists:"Mark Knight, Cassimm, Chus & Ceballos, Crusy, Essel, Hatiras, Leftwing : Kody, Maxinne, Wheats",genre:['techhouse'],matchKeywords:['toolroom','mark knight','tech house','chus ceballos'],summary:"Toolroom Records open-air in Wynwood.",hype:4,mentions:3,bandwagon:1},
  {id:31,day:'thu',dayLabel:'Thu Mar 26',name:"RAW CUTS: DJ Tennis + Gerd Janson",venue:"Watson Island Park",type:'openair',time:"3–10pm",artists:"DJ Tennis, Gerd Janson, Bakke, Mai Iachetti",genre:['deephouse','minimal'],matchKeywords:['dj tennis','gerd janson','running back'],summary:"DJ Tennis and Gerd Janson outdoors at Watson Island.",hype:4,mentions:2,bandwagon:2},
  {id:32,day:'thu',dayLabel:'Thu Mar 26',name:"Breakaway Beach: Bob Sinclar",venue:"National Hotel",type:'pool',time:"12pm–11pm",artists:"Bob Sinclar, Bella Grazia, Dalva, Devault, Linska",genre:['disco','deephouse'],matchKeywords:['bob sinclar','disco house','french house'],summary:"Bob Sinclar brings French disco house poolside.",hype:3,mentions:2,bandwagon:3},
  {id:33,day:'thu',dayLabel:'Thu Mar 26',name:"DEADBEATS 10 Year Anniversary",venue:"MANA Wynwood",type:'warehouse',time:"9pm–5am",artists:"Zeds Dead, Boogie T, Bro Safari, DISTINCT MOTIVE, Aych, Casey Club",genre:['bass'],matchKeywords:['zeds dead','deadbeats','bass music','dubstep'],summary:"Zeds Dead's DEADBEATS celebrates 10 years. Heavy bass warehouse.",hype:4,mentions:3,bandwagon:3},
  {id:34,day:'thu',dayLabel:'Thu Mar 26',name:"Cosmic Gate & Friends",venue:"CLUTCH",type:'club',time:"9pm–5am",artists:"Cosmic Gate, Estiva, Pretty Pink, Luccio, Anunnakis",genre:['trance','progressive'],matchKeywords:['cosmic gate','trance','wake your mind'],summary:"Trance legends Cosmic Gate with Estiva and Pretty Pink.",hype:3,mentions:2,bandwagon:3},
  {id:35,day:'thu',dayLabel:'Thu Mar 26',name:"Infected Mushroom + John 00 Fleming",venue:"Mazuma",type:'club',time:"9pm–5am",artists:"Infected Mushroom, John 00 Fleming",genre:['trance','progressive'],matchKeywords:['infected mushroom','john 00 fleming','psytrance'],summary:"Psytrance meets progressive. Cult followings collide.",hype:3,mentions:2,bandwagon:3},
  {id:36,day:'thu',dayLabel:'Thu Mar 26',name:"AUDIEN: Progressive House Never Dies",venue:"MIDLINE Miami",type:'club',time:"10pm–5am",artists:"Audien, Justin Mylo, Lucas & Steve, Mike Williams, Luke Alexander",genre:['progressive'],matchKeywords:['audien','progressive house','lucas steve'],summary:"Audien: anthemic, uplifting, euphoric progressive house.",hype:3,mentions:2,bandwagon:1},
  {id:37,day:'thu',dayLabel:'Thu Mar 26',name:"4B & Friends",venue:"UVA Wynwood",type:'club',time:"9pm–4am",artists:"4B, Craze, Good Times Ahead, Ricky Remedy, Stevie G",genre:['bass','hiphop'],matchKeywords:['4b','gta','craze','jersey club','trap'],summary:"Bass and trap heavyweights in Wynwood.",hype:3,mentions:2,bandwagon:1},
  {id:38,day:'thu',dayLabel:'Thu Mar 26',name:"Ultra Naté's DEEP SUGAR",venue:"The Triangle at Little River",type:'club',time:"8pm–3am",artists:"Ultra Naté, Soul Clap, Rissa Garcia",genre:['disco','deephouse'],matchKeywords:['ultra nate','soul clap','deep sugar'],summary:"Ultra Naté with Soul Clap. Classic house meets disco funk.",hype:3,mentions:2,bandwagon:1},
  {id:39,day:'thu',dayLabel:'Thu Mar 26',name:"Factory Town Day 2: Jamie Jones Paradise",venue:"Factory Town",type:'warehouse',time:"10pm–7am",artists:"Jamie Jones, Archie Hamilton, Adrián Mills, Alejo, Bad Boombox, ATRIP, Meduza, James Hype, Cole Knight",genre:['techhouse','minimal'],matchKeywords:['jamie jones','paradise','hot creations','archie hamilton','meduza','james hype'],summary:"Jamie Jones brings Paradise to Factory Town. Multi-stage warehouse.",hype:5,mentions:4,bandwagon:2},

  // ── FRIDAY MARCH 27 ────────────────────────────────────────────────────────
  {id:40,day:'fri',dayLabel:'Fri Mar 27',name:"Knee Deep in Miami: Hot Since 82",venue:"Sagamore Hotel",type:'pool',time:"1pm–11pm",artists:"Hot Since 82, Luuk van Dijk, Demi Riquísimo, Mai Iachetti, Prunk",genre:['techhouse','deephouse'],matchKeywords:['hot since 82','knee deep in sound','luuk van dijk'],summary:"Knee Deep in Sound label showcase. Hot Since 82 headlines.",hype:5,mentions:5,bandwagon:3},
  {id:41,day:'fri',dayLabel:'Fri Mar 27',name:"Solid Grooves at Club Space",venue:"Club Space",type:'club',time:"11pm–10am",artists:"Michael Bibi, ChaseWest, KinAhau, Ben Sterling, Pawsa, Carlita (rumored)",genre:['techhouse','minimal'],matchKeywords:['solid grooves','michael bibi','minimal house','chasewest','carlita','pawsa'],summary:"Solid Grooves: marathon sets, packed floors. One of the hottest brands in global house.",hype:5,mentions:6,bandwagon:3},
  {id:42,day:'fri',dayLabel:'Fri Mar 27',name:"Black Coffee at LIV",venue:"LIV Nightclub",type:'club',time:"11:30pm–5am",artists:"Black Coffee",genre:['afrohouse','deephouse'],matchKeywords:['black coffee','afro house','south african house'],summary:"Black Coffee's Friday night at LIV. Deep, spiritual Afro-house.",hype:5,mentions:5,bandwagon:4},
  {id:43,day:'fri',dayLabel:'Fri Mar 27',name:"Chris Lake & Eats Everything: Black Book",venue:"Toe Jam Backlot",type:'club',time:"8pm–3am",artists:"Chris Lake, Eats Everything, Gio Lucca, Jackie Hollander, Marco Lys",genre:['techhouse'],matchKeywords:['chris lake','eats everything','black book records'],summary:"Chris Lake and Eats Everything — two flavors of fun.",hype:4,mentions:4,bandwagon:4},
  {id:44,day:'fri',dayLabel:'Fri Mar 27',name:"Shimza at Jungle Island",venue:"Jungle Island",type:'openair',time:"7pm–3am",artists:"Shimza, Bedouin, Francis Mercier, Arodes, FALYN",genre:['afrohouse','deephouse','melodic'],matchKeywords:['shimza','bedouin','francis mercier','afro house'],summary:"Shimza with Bedouin and Francis Mercier at Jungle Island.",hype:4,mentions:3,bandwagon:2},
  {id:45,day:'fri',dayLabel:'Fri Mar 27',name:"Ministry of Sound × Hard Times: Dennis Ferrer",venue:"Sable Miami",type:'club',time:"7pm–4am",artists:"Dennis Ferrer, Derrick Carter, Chuck Daniels, Doorly, Fletch",genre:['deephouse','disco'],matchKeywords:['dennis ferrer','derrick carter','ministry of sound','hard times'],summary:"Two legendary UK club institutions. Soulful grooves and deep house.",hype:4,mentions:4,bandwagon:3},
  {id:46,day:'fri',dayLabel:'Fri Mar 27',name:"deadmau5 at Toe Jam",venue:"Toe Jam XL",type:'club',time:"8pm–4am",artists:"deadmau5",genre:['progressive','techno'],matchKeywords:['deadmau5','mau5trap'],summary:"deadmau5 headline set at Toe Jam XL.",hype:5,mentions:4,bandwagon:5},
  {id:47,day:'fri',dayLabel:'Fri Mar 27',name:"Diplo at E11EVEN",venue:"E11EVEN Miami",type:'club',time:"8pm–10am",artists:"Diplo, AM75",genre:['hiphop','bass','techhouse'],matchKeywords:['diplo','mad decent','higher ground'],summary:"Diplo at E11EVEN. Genre-bending: house to hip-hop to bass.",hype:4,mentions:3,bandwagon:5},
  {id:48,day:'fri',dayLabel:'Fri Mar 27',name:"RESISTANCE: Amelie Lens & Boys Noize",venue:"M2",type:'club',time:"10pm–5am",artists:"Amelie Lens, Boys Noize, ØTTA",genre:['techno'],matchKeywords:['amelie lens','boys noize','resistance','hard techno'],summary:"Amelie Lens and Boys Noize bring peak-time techno to RESISTANCE.",hype:5,mentions:5,bandwagon:4},
  {id:49,day:'fri',dayLabel:'Fri Mar 27',name:"HUGEL: The Originals HIIDE",venue:"National Hotel",type:'pool',time:"12pm–11pm",artists:"HUGEL, Amal Nemer, Frank Storm",genre:['melodic','techhouse'],matchKeywords:['hugel','hiide'],summary:"HIIDE poolside Friday with HUGEL headlining.",hype:3,mentions:2},
  {id:50,day:'fri',dayLabel:'Fri Mar 27',name:"Soundgarden Cruise: Dubfire b2b Nick Warren",venue:"Yacht / Miami",type:'cruise',time:"3:30–8:30pm",artists:"Dubfire b2b Nick Warren",genre:['techno','melodic'],matchKeywords:['dubfire','nick warren','soundgarden'],summary:"B2b on a boat at sunset. Special format.",hype:4,mentions:3},
  {id:51,day:'fri',dayLabel:'Fri Mar 27',name:"Seven Lions at MIDLINE",venue:"MIDLINE Miami",type:'club',time:"9pm–3am",artists:"Seven Lions, Andrew Bayer, Kill the Noise, Mitis, A Hundred Drums, Quackson",genre:['bass','trance'],matchKeywords:['seven lions','melodic dubstep','anjunabeats','kill the noise'],summary:"Seven Lions' melodic bass and trance crossover.",hype:4,mentions:3},
  {id:52,day:'fri',dayLabel:'Fri Mar 27',name:"Brownies & Lemonade Miami",venue:"MANA Wynwood",type:'warehouse',time:"9pm–5am",artists:"TBA (surprise guests)",genre:['bass','progressive'],matchKeywords:['brownies lemonade','surprise','bass music'],summary:"Famous surprise-guest format. Past editions featured major headliners.",hype:4,mentions:3},
  {id:53,day:'fri',dayLabel:'Fri Mar 27',name:"Ferry Corsten + Giuseppe Ottaviani",venue:"CLUTCH",type:'club',time:"9pm–5am",artists:"Ferry Corsten, Giuseppe Ottaviani, Billy Gillies, Amy Wiles, Luccio",genre:['trance'],matchKeywords:['ferry corsten','giuseppe ottaviani','trance','billy gillies'],summary:"Trance royalty share a bill.",hype:4,mentions:2},
  {id:54,day:'fri',dayLabel:'Fri Mar 27',name:"JOURNEY: Spencer Brown & Eric Luttrell",venue:"Mazuma",type:'club',time:"9pm–5am",artists:"Spencer Brown, Eric Luttrell, Massane, Qrion, Because of Art",genre:['progressive','melodic'],matchKeywords:['spencer brown','eric luttrell','qrion','massane','anjunadeep'],summary:"Anjunadeep-adjacent progressive. Dreamy, introspective.",hype:3,mentions:2},
  {id:55,day:'fri',dayLabel:'Fri Mar 27',name:"House Is A Feeling: Oscar G & DJ Sneak",venue:"1-800-LUCKY",type:'club',time:"6pm–3am",artists:"Oscar G, DJ Sneak, Tony Touch, Harry Romero, Emmaculate, Gettoblaster, DJ Dove",genre:['deephouse','disco'],matchKeywords:['oscar g','dj sneak','harry romero','classic house'],summary:"Miami house royalty. Oscar G, DJ Sneak, Harry Romero.",hype:4,mentions:2},
  {id:56,day:'fri',dayLabel:'Fri Mar 27',name:"EDX Presents No Xcuses",venue:"Nikki Beach",type:'pool',time:"12pm–8pm",artists:"EDX",genre:['progressive','deephouse'],matchKeywords:['edx','no xcuses','progressive house'],summary:"EDX's No Xcuses at Nikki Beach.",hype:3,mentions:2},
  {id:57,day:'fri',dayLabel:'Fri Mar 27',name:"Tgthr: Secret Headliner & Franky Rizardo",venue:"Surfcomber Hotel",type:'pool',time:"12pm–11pm",artists:"Secret Headliner, Franky Rizardo, Mason Collective, Grace Arribas, Amal Nemer",genre:['techhouse','deephouse'],matchKeywords:['franky rizardo','mason collective'],summary:"Tgthr poolside with a secret headliner.",hype:3,mentions:2},
  {id:58,day:'fri',dayLabel:'Fri Mar 27',name:"Factory Town Day 3: Carlita & Friends",venue:"Factory Town",type:'warehouse',time:"9pm–7am",artists:"Carlita, Dan Ghenacia, AC13, Ainonow, Alpha Omega, Hot Since 82, I Hate Models, Skream b2b DJ Seinfeld",genre:['deephouse','melodic','techno'],matchKeywords:['carlita','factory town','dan ghenacia','hot since 82','i hate models','skream'],summary:"Factory Town night 3. Carlita, Hot Since 82, I Hate Models, Skream b2b DJ Seinfeld.",hype:5,mentions:4},

  // ── SATURDAY MARCH 28 ──────────────────────────────────────────────────────
  {id:59,day:'sat',dayLabel:'Sat Mar 28',name:"Danny Tenaglia + Nicole Moudaber",venue:"Sagamore Hotel",type:'pool',time:"1pm–11pm",artists:"Danny Tenaglia, Nicole Moudaber, Jonathan Cowan, Romina Mazzini",genre:['techno','deephouse'],matchKeywords:['danny tenaglia','nicole moudaber','techno'],summary:"Two legends poolside. Tenaglia's groove meets Moudaber's power.",hype:5,mentions:6},
  {id:60,day:'sat',dayLabel:'Sat Mar 28',name:"Marco Carola: Music On",venue:"Club Space",type:'club',time:"11pm–open",artists:"Marco Carola",genre:['techno','minimal'],matchKeywords:['marco carola','music on','minimal techno'],summary:"Music On is a religion. Marco Carola at Space.",hype:5,mentions:6},
  {id:61,day:'sat',dayLabel:'Sat Mar 28',name:"Factory Town: Adam Beyer & Friends",venue:"Factory Town",type:'warehouse',time:"9pm–7am",artists:"Adam Beyer, Bart Skils b2b Marco Faraone, Pawsa b2b Luciano, Joris Voorn, Ben Sterling, Tiga, Ranger Trucco, Anetha, Ammo Avenue",genre:['techno','techhouse','minimal'],matchKeywords:['factory town','adam beyer','drumcode','joris voorn','pawsa','ben sterling','anetha','bart skils'],summary:"Multi-stage warehouse. Drumcode energy + groove selectors. Week's biggest lineup.",hype:5,mentions:7},
  {id:62,day:'sat',dayLabel:'Sat Mar 28',name:"MK & Armand Van Helden: Area 10",venue:"Surfcomber Hotel",type:'pool',time:"12pm–11pm",artists:"MK, Armand Van Helden",genre:['disco','deephouse'],matchKeywords:['mk','armand van helden','disco house','area 10'],summary:"MK and Armand Van Helden: a disco-house dream.",hype:4,mentions:5},
  {id:63,day:'sat',dayLabel:'Sat Mar 28',name:"RESISTANCE: Boris Brejcha, Miss Monique",venue:"M2 Miami",type:'club',time:"10pm–5am",artists:"Boris Brejcha, Miss Monique, Brina Knauss",genre:['techno','melodic'],matchKeywords:['boris brejcha','miss monique','high-tech minimal','resistance'],summary:"Boris Brejcha's high-tech minimal + Miss Monique's melodic journey.",hype:5,mentions:5},
  {id:64,day:'sat',dayLabel:'Sat Mar 28',name:"Adriatique at LIV",venue:"LIV Nightclub",type:'club',time:"11:30pm–late",artists:"Adriatique, MAXI MERAKI",genre:['melodic','deephouse'],matchKeywords:['adriatique','melodic techno','afterlife'],summary:"Swiss duo Adriatique bring ethereal melodic sound to LIV.",hype:4,mentions:4},
  {id:65,day:'sat',dayLabel:'Sat Mar 28',name:"Desert Hearts Open-Air",venue:"UVA Wynwood",type:'openair',time:"4pm–4am",artists:"Mikey Lion, Lee Reynolds, Eats Everything, Kevin Knapp, Life on Planets, Soul Clap, Kyle Walker, Fulano, JIMII",genre:['deephouse','techhouse'],matchKeywords:['desert hearts','eats everything','soul clap','mikey lion'],summary:"Desert Hearts open-air in Wynwood. Cosmic good energy.",hype:4,mentions:4},
  {id:66,day:'sat',dayLabel:'Sat Mar 28',name:"MEDUZA: The Originals Present HIIDE",venue:"National Hotel",type:'pool',time:"12pm–11pm",artists:"MEDUZA, Chelina Manuhutu b2b Tini Gessler, Bassel Darwish, Joe Vanditti, Above Ground, BFoxx, Genesi",genre:['melodic','techhouse'],matchKeywords:['meduza','melodic house','chelina manuhutu'],summary:"MEDUZA headline HIIDE at the National Hotel.",hype:5,mentions:5},
  {id:67,day:'sat',dayLabel:'Sat Mar 28',name:"Black Coffee at Hialeah Park",venue:"Hialeah Park Casino",type:'warehouse',time:"6pm–1am",artists:"Black Coffee, Carlita, Kaz James",genre:['afrohouse','deephouse'],matchKeywords:['black coffee','afro house','carlita','kaz james'],summary:"Black Coffee at the racetrack with Carlita and Kaz James.",hype:5,mentions:7},
  {id:68,day:'sat',dayLabel:'Sat Mar 28',name:"Anjunadeep Open Air Miami",venue:"Wynwood Marketplace",type:'openair',time:"3pm–12am",artists:"Eli & Fur, Amtrac, Because of Art, CRi, Dosem, Jody Wisternoff, Lane 8 (rumored)",genre:['progressive','melodic','deephouse'],matchKeywords:['anjunadeep','eli fur','amtrac','cri','progressive house','lane 8'],summary:"Anjunadeep open-air in Wynwood. Deep, melodic, atmospheric.",hype:5,mentions:4},
  {id:69,day:'sat',dayLabel:'Sat Mar 28',name:"Louie Vega & Friends: Moodymann & Karizma",venue:"ZeyZey",type:'club',time:"3–10pm",artists:"Louie Vega, Moodymann, Anané, Karizma",genre:['deephouse','disco'],matchKeywords:['louie vega','moodymann','karizma','masters at work'],summary:"Louie Vega, Moodymann, Karizma. Masters At Work meets Detroit soul.",hype:5,mentions:3},
  {id:70,day:'sat',dayLabel:'Sat Mar 28',name:"Steve Aoki: 30 Years of Dim Mak",venue:"E11EVEN Miami",type:'club',time:"8pm–10am",artists:"Steve Aoki",genre:['bass','hiphop'],matchKeywords:['steve aoki','dim mak'],summary:"Steve Aoki celebrates 30 years of Dim Mak at E11EVEN.",hype:4,mentions:4},
  {id:71,day:'sat',dayLabel:'Sat Mar 28',name:"LALALAND: Green Velvet & Cajmere",venue:"Toe Jam Backlot",type:'club',time:"8pm–3am",artists:"Green Velvet, Cajmere, AYYBO, DISCIP, Jkatz, OMRI",genre:['techhouse','deephouse'],matchKeywords:['green velvet','cajmere','chicago house','omri'],summary:"Green Velvet and Cajmere — two sides of Curtis Jones.",hype:4,mentions:3},
  {id:72,day:'sat',dayLabel:'Sat Mar 28',name:"Gordo at RC Cola Plant",venue:"RC Cola Plant",type:'warehouse',time:"10pm–5am",artists:"Gordo",genre:['techhouse','techno'],matchKeywords:['gordo','carnage','tech house'],summary:"Gordo at RC Cola Plant. Dark warehouse tech house.",hype:4,mentions:3},
  {id:73,day:'sat',dayLabel:'Sat Mar 28',name:"Rodriguez Jr. Yacht Cruise",venue:"Luxury Yacht",type:'cruise',time:"3–7pm",artists:"Rodriguez Jr., Sydney Blu, Darin Epsilon, Min the Universe",genre:['melodic','deephouse'],matchKeywords:['rodriguez jr','melodic house'],summary:"Sunset cruise with Rodriguez Jr.'s cinematic melodic house.",hype:4,mentions:2},
  {id:74,day:'sat',dayLabel:'Sat Mar 28',name:"Cosmic Gate Sunset Cruise",venue:"Hyatt Regency Dock",type:'cruise',time:"3pm–8pm",artists:"Cosmic Gate, Luccio",genre:['trance','progressive'],matchKeywords:['cosmic gate','trance'],summary:"Cosmic Gate on a sunset cruise. Trance on open water.",hype:4,mentions:2},
  {id:75,day:'sat',dayLabel:'Sat Mar 28',name:"Gabriel & Dresden: Stories We Tell",venue:"Mazuma",type:'club',time:"9pm–3am",artists:"Gabriel & Dresden",genre:['trance','progressive'],matchKeywords:['gabriel dresden','anjunabeats'],summary:"Gabriel & Dresden's emotional progressive trance.",hype:3,mentions:2},
  {id:76,day:'sat',dayLabel:'Sat Mar 28',name:"A-Trak & Friends × Fool's Gold",venue:"ZeyZey",type:'club',time:"11pm–4am",artists:"A-Trak, Dennis Ferrer, DJ Slugo, Illyus & Barrientos, Monty Kiddo",genre:['disco','hiphop','deephouse'],matchKeywords:['a-trak','fools gold','dennis ferrer'],summary:"A-Trak brings Fool's Gold. Eclectic, genre-spanning late-night.",hype:4,mentions:2},
  {id:77,day:'sat',dayLabel:'Sat Mar 28',name:"Valentino Khan & Friends",venue:"MAD Club Wynwood",type:'club',time:"10pm–3am",artists:"Valentino Khan, DJ Susan, Marten Hørger, OKAYVAL, Proppa",genre:['bass','hiphop'],matchKeywords:['valentino khan','bass house'],summary:"Valentino Khan's bass house meets Wynwood.",hype:3,mentions:2},
  {id:78,day:'sat',dayLabel:'Sat Mar 28',name:"Odd Mob & Lauren Lane",venue:"MIDLINE Miami",type:'club',time:"10pm–5am",artists:"Odd Mob, Lauren Lane, Loofy, Yokai",genre:['techhouse','bass'],matchKeywords:['odd mob','lauren lane'],summary:"Odd Mob and Lauren Lane: tech house grooves with a harder edge.",hype:3,mentions:2},

  // ── SUNDAY MARCH 29 ────────────────────────────────────────────────────────
  {id:79,day:'sun',dayLabel:'Sun Mar 29',name:"Glitterbox Closing",venue:"Sagamore Hotel",type:'pool',time:"1pm–11pm",artists:"Skream, Derrick Carter, Gerd Janson, Natasha Diggs, The Brothers Macklovitch, Aline Rocha, Yasmin",genre:['disco','deephouse'],matchKeywords:['glitterbox','skream','derrick carter','gerd janson','disco','natasha diggs'],summary:"Glitterbox closing. Skream + Derrick Carter + Gerd Janson.",hype:5,mentions:6},
  {id:80,day:'sun',dayLabel:'Sun Mar 29',name:"RESISTANCE Closing: Carl Cox & Maceo Plex",venue:"M2",type:'club',time:"10pm–5am",artists:"Carl Cox, Maceo Plex, Airrica",genre:['techno'],matchKeywords:['carl cox','maceo plex','resistance'],summary:"Carl Cox and Maceo Plex close RESISTANCE. Unmissable.",hype:5,mentions:6},
  {id:81,day:'sun',dayLabel:'Sun Mar 29',name:"Elrow Miami at Factory Town",venue:"Factory Town",type:'festival',time:"10pm–7am",artists:"LP Giobbi, Ilario Alicante, Jay De Lys, Matroda, Emjie, Archie Hamilton, Bontan, ChaseWest, Dan Molinari",genre:['techhouse','techno'],matchKeywords:['elrow','ilario alicante','lp giobbi','matroda'],summary:"Elrow's colorful, theatrical party at Factory Town. Closing night.",hype:5,mentions:5},
  {id:82,day:'sun',dayLabel:'Sun Mar 29',name:"Claptone Presents The Masquerade",venue:"Surfcomber Hotel",type:'pool',time:"12pm–11pm",artists:"Claptone",genre:['deephouse','disco'],matchKeywords:['claptone','masquerade'],summary:"Claptone's iconic Masquerade. Masks, mystery, deep house.",hype:4,mentions:3},
  {id:83,day:'sun',dayLabel:'Sun Mar 29',name:"James Hype: HIIDE",venue:"National Hotel",type:'pool',time:"12pm–11pm",artists:"James Hype, Classmatic, Benjamin Lloyd, BFoxx, Alves, DJ Tucci",genre:['techhouse'],matchKeywords:['james hype','hiide'],summary:"James Hype closes the HIIDE pool series.",hype:4,mentions:3},
  {id:84,day:'sun',dayLabel:'Sun Mar 29',name:"Vintage Culture at E11EVEN",venue:"E11EVEN Miami",type:'club',time:"8pm–10am",artists:"Vintage Culture",genre:['techhouse','deephouse'],matchKeywords:['vintage culture','brazilian house'],summary:"Vintage Culture closes E11EVEN's MMW series.",hype:4,mentions:3},
  {id:85,day:'sun',dayLabel:'Sun Mar 29',name:"Cristoph Presents COS Miami",venue:"Mazuma",type:'club',time:"9pm–5am",artists:"Cristoph, Jeremy Olander, Dirty South, Dimuth K, Michael Anthony",genre:['progressive','melodic'],matchKeywords:['cristoph','jeremy olander','dirty south'],summary:"Cristoph's COS with Jeremy Olander and Dirty South.",hype:4,mentions:2},
  {id:86,day:'sun',dayLabel:'Sun Mar 29',name:"Anjunabeats Miami",venue:"MAD LIVE",type:'club',time:"10pm–4am",artists:"Mat Zo, Genix, Grum, Amy Wiles, Leena Punks",genre:['trance','progressive'],matchKeywords:['anjunabeats','mat zo','genix','grum'],summary:"Anjunabeats with Mat Zo, Genix, and Grum.",hype:4,mentions:3},
  {id:87,day:'sun',dayLabel:'Sun Mar 29',name:"MoBlack Records Closing",venue:"Toe Jam Backlot",type:'club',time:"8pm–4am",artists:"Francis Mercier, Caiiro, Ape Drums, Avö, Luna Mar",genre:['afrohouse','deephouse'],matchKeywords:['moblack','francis mercier','caiiro'],summary:"MoBlack closing. Afro-house rhythms to end the week.",hype:3,mentions:2},
  {id:88,day:'sun',dayLabel:'Sun Mar 29',name:"30+ Hour Closing Party",venue:"Space Miami",type:'club',time:"12am–12am+",artists:"TBA",genre:['techhouse','techno','deephouse'],matchKeywords:['space miami','closing party','marathon'],summary:"Space Miami's legendary 30+ hour closing. Ultimate marathon.",hype:5,mentions:5},
  {id:89,day:'sun',dayLabel:'Sun Mar 29',name:"Deeperfect Showcase",venue:"Mode",type:'club',time:"10pm–5am",artists:"Stefano Noferini, Dimmish, Joe Vanditti, Mandiz, Slugg",genre:['techhouse'],matchKeywords:['stefano noferini','deeperfect'],summary:"Stefano Noferini's Deeperfect label showcase.",hype:3,mentions:1},
  {id:90,day:'sun',dayLabel:'Sun Mar 29',name:"AC Slater & Friends",venue:"MAD Club Wynwood",type:'club',time:"10pm–3am",artists:"AC Slater",genre:['bass','techhouse'],matchKeywords:['ac slater','night bass','bass house'],summary:"AC Slater's Night Bass: bass house closing night.",hype:3,mentions:2},
  {id:91,day:'thu',dayLabel:'Thu Mar 26',name:"PAWSA & Friends at LIV",venue:"LIV Nightclub",type:'club',time:"11:30pm–5am",artists:"PAWSA, OMRI, KinAhau",genre:['techhouse','minimal'],matchKeywords:['pawsa','omri','kinahau','minimal house'],summary:"PAWSA headlines LIV with OMRI and KinAhau support. Groovy minimal house.",hype:4,mentions:3},
  {id:92,day:'fri',dayLabel:'Fri Mar 27',name:"OMRI at Wynwood Studios",venue:"MAD Club Wynwood",type:'club',time:"10pm–4am",artists:"OMRI, TBA",genre:['techhouse','minimal'],matchKeywords:['omri','wynwood studios','tech house'],summary:"OMRI brings his signature groovy tech house sound to Wynwood.",hype:3,mentions:2},
  {id:93,day:'sat',dayLabel:'Sat Mar 28',name:"Lunasol: OMRI",venue:"Jolene Sound Room",type:'club',time:"10pm–4am",artists:"OMRI, TBA",genre:['techhouse','deephouse','minimal'],matchKeywords:['omri','lunasol','tech house'],summary:"OMRI's Lunasol showcase. Intimate setting for deep grooves.",hype:3,mentions:2},
];
